<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Max Mathues">

<title>Problem Set 03: Data Wrangling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="PS03_source_files/libs/clipboard/clipboard.min.js"></script>
<script src="PS03_source_files/libs/quarto-html/quarto.js"></script>
<script src="PS03_source_files/libs/quarto-html/popper.min.js"></script>
<script src="PS03_source_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PS03_source_files/libs/quarto-html/anchor.min.js"></script>
<link href="PS03_source_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PS03_source_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PS03_source_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PS03_source_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PS03_source_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="PS03_source.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem Set 03: Data Wrangling</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Max Mathues </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Last modified on September 06, 2023 21:39:57 Eastern Daylight Time</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>In this problem set we will practice some of the key data manipulation tasks for describing, summarizing, and working with data. We will specifically review the following functions from the <code>dplyr</code> package:</p>
<ul>
<li><code>select</code></li>
<li><code>mutate</code></li>
<li><code>summarize</code></li>
<li><code>arrange</code></li>
<li><code>filter</code></li>
<li><code>group_by</code></li>
<li><code>%&gt;%</code></li>
</ul>
<p>In addition we will review how to save objects using the <code>&lt;-</code> assignment operator.</p>
<p>The following code loads the necessary packages for this problem set:</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="the-data" class="level1">
<h1>The Data</h1>
<p>The following code chunk loads the data set <code>txhousing</code> and displays the data using <code>glimpse</code>:</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(txhousing)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(txhousing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 8,602
Columns: 9
$ city      &lt;chr&gt; "Abilene", "Abilene", "Abilene", "Abilene", "Abilene", "Abil…
$ year      &lt;int&gt; 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, …
$ month     &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, …
$ sales     &lt;dbl&gt; 72, 98, 130, 98, 141, 156, 152, 131, 104, 101, 100, 92, 75, …
$ volume    &lt;dbl&gt; 5380000, 6505000, 9285000, 9730000, 10590000, 13910000, 1263…
$ median    &lt;dbl&gt; 71400, 58700, 58100, 68600, 67300, 66900, 73500, 75000, 6450…
$ listings  &lt;dbl&gt; 701, 746, 784, 785, 794, 780, 742, 765, 771, 764, 721, 658, …
$ inventory &lt;dbl&gt; 6.3, 6.6, 6.8, 6.9, 6.8, 6.6, 6.2, 6.4, 6.5, 6.6, 6.2, 5.7, …
$ date      &lt;dbl&gt; 2000.000, 2000.083, 2000.167, 2000.250, 2000.333, 2000.417, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#txhousing &lt;- txhousing[sample(1:802),]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>These data are about housing in Texas. Each row is monthly data for a given city in Texas in a given year. There are multiple years of data for each city.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Examine <code>txhousing</code> in the data viewer. You can accomplish this two different ways: A) click on the name of the data in the Environment pane, or b) type <code>View(txhousing)</code> in the <strong>console</strong>. What is the last city listed in the data set (in row 8602)? Use <code>R</code> code to programatically find the last city in <code>txhousing</code>.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 1 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 1 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(txhousing)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>txhousing[<span class="dv">8602</span>,<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  city         
  &lt;chr&gt;        
1 Wichita Falls</code></pre>
</div>
</div>
<ul>
<li>Wichita Falls is the last city in txhousing</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 2">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Examine the variable descriptions by typing <code>?txhousing</code> in the <strong>console</strong>. What is the <code>listings</code> variable in this data set?</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 2 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 2 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>The documentation states that listings represents the total active listings in txhousing.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="data-wrangling-review" class="level1">
<h1>Data Wrangling Review</h1>
<section id="select" class="level2">
<h2 class="anchored" data-anchor-id="select"><code>select()</code></h2>
<p>Sometimes we want to pull out or extract just one or two columns of data. The following code will extract only the columns in the data set for the variables <code>sales</code> and <code>volume</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>txhousing <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sales, volume)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>%&gt;%</code> symbol is called the <strong>piping</strong> operator. Here, it takes the <code>txhousing</code> <strong>data frame</strong> and “pipes” or feeds it into the <code>select</code> function. You can think of the <code>%&gt;%</code> symbol as the word “then”.</p>
<p>Note that an assignment operator (<code>&lt;-</code>) was not used in the code; consequently the selected values are not saved. In the following code, the results are saved in a data frame <strong>ALSO</strong> called <code>txhousing</code>. By putting <code>-</code> in front of the <code>date</code> variable <code>R</code> selects all variables <strong>except</strong> the <code>date</code> variable.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>txhousing <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>date)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(txhousing) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  city     year month sales   volume median listings inventory
  &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Abilene  2000     1    72  5380000  71400      701       6.3
2 Abilene  2000     2    98  6505000  58700      746       6.6
3 Abilene  2000     3   130  9285000  58100      784       6.8
4 Abilene  2000     4    98  9730000  68600      785       6.9
5 Abilene  2000     5   141 10590000  67300      794       6.8
6 Abilene  2000     6   156 13910000  66900      780       6.6</code></pre>
</div>
</div>
</div>
</div>
<p>If you examine <code>txhousing</code> in the data viewer, the <code>date</code> variable is no longer included.</p>
</section>
<section id="filter" class="level2">
<h2 class="anchored" data-anchor-id="filter"><code>filter()</code></h2>
<p>The filter function allows you to pull out just the <strong>rows</strong> (cases or observations) you want, based on some criteria in <strong>one of the columns</strong>.</p>
<p>Imagine we wanted to reduce the data set to include data for only 2012 in the city of Austin. The code chunk below filters the <code>txhousing</code> to only include rows in which the year is 2012 <strong>and</strong> the city is Austin. The results are saved in a new data frame called <code>austin_12</code>.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>austin_12 <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2012</span> <span class="sc">&amp;</span> city <span class="sc">==</span> <span class="st">"Austin"</span>) </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Or filter(year == 2012, city == "Austin")</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(austin_12)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  city    year month sales    volume median listings inventory
  &lt;chr&gt;  &lt;int&gt; &lt;int&gt; &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Austin  2012     1  1182 265821275 177400     7432       4.2
2 Austin  2012     2  1415 353527608 191600     7738       4.3
3 Austin  2012     3  2083 533800484 198600     8186       4.5
4 Austin  2012     4  2128 563288160 207400     8239       4.5
5 Austin  2012     5  2611 705383898 210200     8465       4.5
6 Austin  2012     6  2837 791281075 216000     8641       4.5</code></pre>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that we use <code>==</code> to identify the desired criteria.</p>
</div>
</div>
<p>What if we wanted to restrict our data set to only years before 2004 and the City of Austin? Below we use the <code>&lt;</code> symbol to accomplish this. Note we did not <strong>SAVE</strong> these results in a new data frame…so no new data frame showed up in our Environment pane, but the results print out immediately below the code chunk.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>txhousing <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&lt;</span> <span class="dv">2004</span>, city <span class="sc">==</span> <span class="st">"Austin"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  city    year month sales    volume median listings inventory
  &lt;chr&gt;  &lt;int&gt; &lt;int&gt; &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Austin  2000     1  1025 173053635 133700     3084       2  
2 Austin  2000     2  1277 226038438 134000     2989       2  
3 Austin  2000     3  1603 298557656 136700     3042       2  
4 Austin  2000     4  1556 289197960 136900     3192       2.1
5 Austin  2000     5  1980 393073774 144700     3617       2.3
6 Austin  2000     6  1885 368290072 148800     3799       2.4</code></pre>
</div>
</div>
</div>
</div>
<p>What if we wanted to use multiple cities? Below we use the <code>|</code> symbol to indicate that the city could be Austin <strong>OR</strong> Abilene. In this case, we <strong>saved</strong> these results as a new data frame called <code>aust_ab</code> that appears in your Environment pane.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>aust_ab <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(city <span class="sc">==</span> <span class="st">"Austin"</span> <span class="sc">|</span> city <span class="sc">==</span> <span class="st">"Abilene"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(aust_ab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  city     year month sales   volume median listings inventory
  &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Abilene  2000     1    72  5380000  71400      701       6.3
2 Abilene  2000     2    98  6505000  58700      746       6.6
3 Abilene  2000     3   130  9285000  58100      784       6.8
4 Abilene  2000     4    98  9730000  68600      785       6.9
5 Abilene  2000     5   141 10590000  67300      794       6.8
6 Abilene  2000     6   156 13910000  66900      780       6.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(aust_ab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  city    year month sales     volume median listings inventory
  &lt;chr&gt;  &lt;int&gt; &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Austin  2015     2  1978  595625521 245300     5733       2.2
2 Austin  2015     3  2677  885779822 253900     5906       2.3
3 Austin  2015     4  2801  931744729 270300     6560       2.5
4 Austin  2015     5  2999 1026501450 271200     7009       2.7
5 Austin  2015     6  3301 1086689918 270200     7419       2.8
6 Austin  2015     7  3466 1150381553 264600     7913       3  </code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="mutate" class="level2">
<h2 class="anchored" data-anchor-id="mutate"><code>mutate()</code></h2>
<p>The mutate function can add new columns (variables) to a data frame. For instance, the following will add a new column to the data called <code>vol_100k</code> that expresses volume in units of $100,000.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>txhousing <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vol_100k =</span> volume<span class="sc">/</span><span class="dv">100000</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(txhousing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  city     year month sales   volume median listings inventory vol_100k
  &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 Abilene  2000     1    72  5380000  71400      701       6.3     53.8
2 Abilene  2000     2    98  6505000  58700      746       6.6     65.0
3 Abilene  2000     3   130  9285000  58100      784       6.8     92.8
4 Abilene  2000     4    98  9730000  68600      785       6.9     97.3
5 Abilene  2000     5   141 10590000  67300      794       6.8    106. 
6 Abilene  2000     6   156 13910000  66900      780       6.6    139. </code></pre>
</div>
</div>
</div>
</div>
<p>Note that we <strong>SAVED</strong> these results in new data frame called <code>txhousing</code>. This therefore <strong>overwrote</strong> the old <code>txhousing</code> data frame with a new version that contains this column. You can open the <code>txhousing</code> data frame in the viewer to confirm that it now contains this new column.</p>
</section>
<section id="summarize" class="level2">
<h2 class="anchored" data-anchor-id="summarize"><code>summarize()</code></h2>
<p>One of the first tasks in data analysis is often to get descriptive statistics that help to understand the central tendency and variability in the data. The <code>summarize()</code> command can take a column of data, and reduce it to a summary statistic.</p>
<p>For instance, the code below uses the <code>austin_12</code> data set made earlier to calculate the mean monthly number of <code>sales</code> in Austin in 2012.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>austin_12 <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">x_bar_sales =</span> <span class="fu">mean</span>(sales))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code tells <code>R</code> to calculate the <code>mean</code> of the variable <code>sales</code>, and to save the results in a variable called <code>x_bar_sales</code>.</p>
<p>You can also calculate multiple summary statistics at once, and even for multiple variables. Below we also calculate a standard deviation <code>sd()</code> of <code>sales</code>, a minimum <code>min()</code> of the <code>volume</code> variable, a maximum <code>max()</code> of the <code>volume</code> variable, etc. The <code>n()</code> calculates sample size…or the number of rows/ cases in the data frame.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>austin_12 <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">x_bar_sales =</span> <span class="fu">mean</span>(sales), </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_sales =</span> <span class="fu">sd</span>(sales), </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_vol =</span> <span class="fu">min</span>(volume), </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_vol =</span> <span class="fu">max</span>(volume), </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">mdn_list =</span> <span class="fu">median</span>(listings), </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">iqr_list =</span> <span class="fu">IQR</span>(listings),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">sample_size =</span> <span class="fu">n</span>()) <span class="ot">-&gt;</span> ans1</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(ans1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">x_bar_sales</th>
<th style="text-align: right;">sd_sales</th>
<th style="text-align: right;">min_vol</th>
<th style="text-align: right;">max_vol</th>
<th style="text-align: right;">mdn_list</th>
<th style="text-align: right;">iqr_list</th>
<th style="text-align: right;">sample_size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2126.75</td>
<td style="text-align: right;">500.8361</td>
<td style="text-align: right;">265821275</td>
<td style="text-align: right;">791281075</td>
<td style="text-align: right;">7925</td>
<td style="text-align: right;">948.75</td>
<td style="text-align: right;">12</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>Note that the names of the elements you calculate are user defined, like <code>xbar_sales</code>, <code>min_vol</code>, and <code>mdn_list</code>. You could customize these names as you like (but don’t use spaces in your names).</p>
</section>
<section id="arrange" class="level2">
<h2 class="anchored" data-anchor-id="arrange"><code>arrange()</code></h2>
<p>You just determined that the maximum volume of monthly sales in Austin in 2012 was a total of $791,281,075 … but what if you wanted to know <strong>WHAT MONTH</strong> that occurred in?</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>austin_12 <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(volume)) <span class="ot">-&gt;</span> ans2</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ans2, <span class="at">n =</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">city</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">month</th>
<th style="text-align: right;">sales</th>
<th style="text-align: right;">volume</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">listings</th>
<th style="text-align: right;">inventory</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Austin</td>
<td style="text-align: right;">2012</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2837</td>
<td style="text-align: right;">791281075</td>
<td style="text-align: right;">216000</td>
<td style="text-align: right;">8641</td>
<td style="text-align: right;">4.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Austin</td>
<td style="text-align: right;">2012</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2604</td>
<td style="text-align: right;">718755768</td>
<td style="text-align: right;">211000</td>
<td style="text-align: right;">8519</td>
<td style="text-align: right;">4.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Austin</td>
<td style="text-align: right;">2012</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2647</td>
<td style="text-align: right;">708540314</td>
<td style="text-align: right;">205100</td>
<td style="text-align: right;">8112</td>
<td style="text-align: right;">4.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>The above code tells <code>R</code> to <code>arrange</code> the rows in the data set based on the <code>volume</code> column and to do so in <code>desc</code>ending order. Consequently, the row with the $791,281,075 in sales is shown at the top. We can see that this <code>volume</code> occurred in the <span class="math inline">\(6^{\text{th}}\)</span> month (June).</p>
</section>
<section id="group_by" class="level2">
<h2 class="anchored" data-anchor-id="group_by"><code>group_by()</code></h2>
<p>Sometimes we also want to calculate summary statistics across different levels of another variable. For instance, here we find the average number of monthly sales that occurred in Abilene and Austin across all years in the data set. Note that we <strong>use the <code>aust_ab</code> data frame</strong> we created earlier, to restrict our analysis to those two cities.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>aust_ab <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(city) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">x_bar_sales =</span> <span class="fu">mean</span>(sales)) <span class="ot">-&gt;</span> results</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">city</th>
<th style="text-align: right;">x_bar_sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Abilene</td>
<td style="text-align: right;">150.4866</td>
</tr>
<tr class="even">
<td style="text-align: left;">Austin</td>
<td style="text-align: right;">1996.6898</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>From the results we can see that there were an average of 150.5 sales per month in Abilene, and 1996.7 sales per month in Austin.</p>
<p>We can give <code>R</code> multiple variables to group by. For instance, the following code returns the mean sales for each month in each city averaged across all the years.</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled" title="R Code">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
R Code
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>aust_ab <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(city, month) <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">x_bar_sales =</span> <span class="fu">mean</span>(sales)) <span class="ot">-&gt;</span> results_ab</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>results_ab <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">city</th>
<th style="text-align: right;">month</th>
<th style="text-align: right;">x_bar_sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Abilene</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">96.3125</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abilene</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">121.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Abilene</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">151.3750</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abilene</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">159.8750</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Abilene</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">177.8750</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abilene</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">190.3125</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>The mean number of sales for Abilene in January (across all years) was 96.3 homes.</p>
</section>
</section>
<section id="independent-practice" class="level1">
<h1>Independent Practice</h1>
<section id="basic-syntax" class="level2">
<h2 class="anchored" data-anchor-id="basic-syntax">Basic Syntax</h2>
<p>This first set of questions will help you practice basic syntax.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 3">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Write a code chunk to remove the inventory variable. Save the results in a data frame called <code>txhousing</code>. Confirm the variable <code>inventory</code> has been removed.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 3 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 3 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>txhousing <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>(inventory))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>txhousing</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8,602 × 8
   city     year month sales   volume median listings vol_100k
   &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1 Abilene  2000     1    72  5380000  71400      701     53.8
 2 Abilene  2000     2    98  6505000  58700      746     65.0
 3 Abilene  2000     3   130  9285000  58100      784     92.8
 4 Abilene  2000     4    98  9730000  68600      785     97.3
 5 Abilene  2000     5   141 10590000  67300      794    106. 
 6 Abilene  2000     6   156 13910000  66900      780    139. 
 7 Abilene  2000     7   152 12635000  73500      742    126. 
 8 Abilene  2000     8   131 10710000  75000      765    107. 
 9 Abilene  2000     9   104  7615000  64500      771     76.2
10 Abilene  2000    10   101  7040000  59300      764     70.4
# ℹ 8,592 more rows</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 4">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 4
</div>
</div>
<div class="callout-body-container callout-body">
<p>Make a data set called <code>dallas_sub</code> that includes data only from the city of Dallas in 2012 and 2013. Show the first six rows of <code>dallas_sub</code>.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 4 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 4 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>dallas_sub <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;</span> <span class="dv">2011</span>, year <span class="sc">&lt;</span> <span class="dv">2014</span>, city <span class="sc">==</span> <span class="st">"Dallas"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dallas_sub, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  city    year month sales     volume median listings vol_100k
  &lt;chr&gt;  &lt;int&gt; &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 Dallas  2012     1  2555  509458081 150800    16721    5095.
2 Dallas  2012     2  3085  634067291 157100    17173    6341.
3 Dallas  2012     3  4068  898320563 167300    17433    8983.
4 Dallas  2012     4  4291  983333297 168700    17632    9833.
5 Dallas  2012     5  5004 1175419749 175100    17726   11754.
6 Dallas  2012     6  5196 1209024869 177900    17587   12090.</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 5">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 5
</div>
</div>
<div class="callout-body-container callout-body">
<p>Add a column to the <code>dallas_sub</code> data set called <code>prct_sold</code> that calculates the percentage of <code>listings</code> that were <code>sold</code> (<code>sales/listings * 100</code>). Be sure to <strong>save</strong> the results into a data frame called <code>dallas_sub</code>. Display the last six rows of <code>dallas_sub</code>.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 5 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 5 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dallas_sub <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;</span> <span class="dv">2011</span>, year <span class="sc">&lt;</span> <span class="dv">2014</span>, city <span class="sc">==</span> <span class="st">"Dallas"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prct_sold =</span> sales<span class="sc">/</span>listings <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(dallas_sub, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  city    year month sales     volume median listings vol_100k prct_sold
  &lt;chr&gt;  &lt;int&gt; &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Dallas  2013     7  6322 1598961793 199200    13685   15990.      46.2
2 Dallas  2013     8  6209 1570480866 198000    13694   15705.      45.3
3 Dallas  2013     9  4941 1181585876 188800    13145   11816.      37.6
4 Dallas  2013    10  4593 1105924279 189200    12728   11059.      36.1
5 Dallas  2013    11  3964  968261356 186600    11895    9683.      33.3
6 Dallas  2013    12  4212 1071755610 194900    10531   10718.      40.0</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 6">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 6
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calculate the <strong>average</strong> percentage of listings that were sold in Dallas <strong>in each month across the years</strong> based on your <code>dallas_sub</code> data set. Save the results of the calculation in a data frame called <code>dallas_summary</code> with the results stored in <code>mean_prct_sold</code>. Display the results of <code>dallas_summary</code>.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 6 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 6 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dallas_summary <span class="ot">&lt;-</span> dallas_sub <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_prct_sold =</span> <span class="fu">mean</span>(prct_sold))</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>dallas_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   month mean_prct_sold
   &lt;int&gt;          &lt;dbl&gt;
 1     1           20.5
 2     2           23.5
 3     3           32.2
 4     4           34.5
 5     5           38.2
 6     6           37.2
 7     7           37.1
 8     8           38.5
 9     9           31.8
10    10           32.1
11    11           30.6
12    12           35.5</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 7">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 7
</div>
</div>
<div class="callout-body-container callout-body">
<p>Arrange the <code>dallas_summary</code> in <code>desc</code>ending order based on the average percentage of listings that were sold in Dallas, so you can see <strong>which month</strong> had the greatest percentage of houses sold in Dallas on average from 2012-2013. You do not need to save the results.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 7 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 7 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>dallas_summary <span class="ot">&lt;-</span> dallas_sub <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month, year) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_prct_sold =</span> <span class="fu">mean</span>(prct_sold)) <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_prct_sold))</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>dallas_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 3
# Groups:   month [12]
   month  year mean_prct_sold
   &lt;int&gt; &lt;int&gt;          &lt;dbl&gt;
 1     5  2013           48.2
 2     7  2013           46.2
 3     8  2013           45.3
 4     6  2013           44.8
 5     4  2013           44.6
 6     3  2013           41.2
 7    12  2013           40.0
 8     9  2013           37.6
 9    10  2013           36.1
10    11  2013           33.3
# ℹ 14 more rows</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="more-advanced-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="more-advanced-wrangling">More Advanced Wrangling</h2>
<p>Please answer the following questions with text and/or code where appropriate. You may have to use multiple <code>dplyr</code> functions to answer each question. Think through the steps of how to get to the answer you are trying to find.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 8">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 8
</div>
</div>
<div class="callout-body-container callout-body">
<p>Run the following code chunk. Study the code, and the output. Explain in your own words what this code chunk calculated. Specifically, compare this code to the code in Problems 4 through 7.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 8 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 8 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>txhousing <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2012</span> <span class="sc">|</span> year <span class="sc">==</span> <span class="dv">2013</span>, city <span class="sc">==</span> <span class="st">"Dallas"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prct_sold =</span> sales<span class="sc">/</span>listings <span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_prct_sold =</span> <span class="fu">mean</span>(prct_sold)) <span class="sc">%&gt;%</span> </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_prct_sold))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   month mean_prct_sold
   &lt;int&gt;          &lt;dbl&gt;
 1     8           38.5
 2     5           38.2
 3     6           37.2
 4     7           37.1
 5    12           35.5
 6     4           34.5
 7     3           32.2
 8    10           32.1
 9     9           31.8
10    11           30.6
11     2           23.5
12     1           20.5</code></pre>
</div>
</div>
<ul>
<li>It is looking at Dallas between 2012-2013 and calculating the mean percentage of houses sold for each month. For instance, it will take January 2012 and January 2013 and print out the average percentage of houses sold between both years.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 9">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 9
</div>
</div>
<div class="callout-body-container callout-body">
<p>In January of 2015, what city had the fewest houses listed for sale? Report the city and the number of houses said city had listed for sale using inline <code>R</code> code.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 9 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 9 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>txhousing2 <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2015</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(listings) <span class="sc">%&gt;%</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(listings)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>txhousing2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 322 × 8
# Groups:   listings [283]
   city        year month sales   volume median listings vol_100k
   &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1 San Marcos  2015     2    19  3984850 170000       83     39.8
 2 San Marcos  2015     1    18  3376703 150000       85     33.8
 3 San Marcos  2015     3    24  4215796 160000       97     42.2
 4 San Marcos  2015     6    39  8808027 190000      101     88.1
 5 San Marcos  2015     5    36  8617000 215000      102     86.2
 6 San Marcos  2015     4    29  6806350 210700      110     68.1
 7 Garland     2015     3   172 25582593 135900      146    256. 
 8 Garland     2015     2   123 19955972 141400      147    200. 
 9 Garland     2015     4   160 24616400 141000      170    246. 
10 Garland     2015     5   195 32018011 151000      177    320. 
# ℹ 312 more rows</code></pre>
</div>
</div>
<ul>
<li>The city I found with the least listings was San Marcos with 83.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 10">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 10
</div>
</div>
<div class="callout-body-container callout-body">
<p>In 2012, in which month were the most houses sold in Texas? Report the month were the most houses sold in Texas and the number of houses sold for that month using inline <code>R</code> code.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 10 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 10 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>txhousing3 <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2012</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month, sales) <span class="sc">%&gt;%</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(sales))</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>txhousing3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 552 × 8
# Groups:   month, sales [530]
   city     year month sales     volume median listings vol_100k
   &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1 Houston  2012     8  7112 1566297243 163900    27090   15663.
 2 Houston  2012     6  6990 1620900791 170700    28834   16209.
 3 Houston  2012     7  6842 1541655520 169300    28514   15417.
 4 Houston  2012     5  6743 1565958406 168000    28819   15660.
 5 Houston  2012    10  5866 1280422125 162100    24828   12804.
 6 Houston  2012     4  5629 1235085496 161100    29111   12351.
 7 Houston  2012    12  5610 1335407998 171000    21632   13354.
 8 Houston  2012     9  5479 1186230552 163300    26019   11862.
 9 Houston  2012    11  5449 1231393037 166700    23592   12314.
10 Houston  2012     3  5389 1200579097 161700    28548   12006.
# ℹ 542 more rows</code></pre>
</div>
</div>
<ul>
<li>The city I found with the most listings was Houston with 7112.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Problem 11">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 11
</div>
</div>
<div class="callout-body-container callout-body">
<p>Generate a <strong>single</strong> table that shows the total number of houses sold in <strong>Austin</strong> in <strong>2000 and 2001</strong> (total over the entire period), &amp; the total number of houses sold in <strong>Dallas</strong> in <strong>2000 and 2001</strong> (total over the entire period). This calculation requires a number of steps, so it might help you to first write out on paper the different steps you will need to take. That will help you set out a “blueprint” for tackling the problem. <strong>Hint</strong>: recall the <code>sum()</code> function can add values.</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Problem 11 Answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problem 11 Answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your code and comments inside the code chunk</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>txhousing5 <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span> </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2000</span> <span class="sc">|</span> year <span class="sc">==</span> <span class="dv">2001</span>, city <span class="sc">==</span> <span class="st">"Austin"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">austin_total_sales =</span> <span class="fu">sum</span>(sales))</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>txhousing6 <span class="ot">&lt;-</span> txhousing <span class="sc">%&gt;%</span> </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2000</span> <span class="sc">|</span> year <span class="sc">==</span> <span class="dv">2001</span>, city <span class="sc">==</span> <span class="st">"Dallas"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dallas_total_sales =</span> <span class="fu">sum</span>(sales))</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="fu">inner_join</span>(<span class="at">x =</span> txhousing5, <span class="at">y =</span> txhousing6, <span class="at">by =</span> <span class="st">"month"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dallas_total_sales, austin_total_sales) <span class="sc">%&gt;%</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  dallas_total_sales austin_total_sales
               &lt;dbl&gt;              &lt;dbl&gt;
1              92438              37013</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="turning-in-your-work" class="level1">
<h1>Turning in Your Work</h1>
<p>You will need to make sure you commit and push all of your changes to the github education repository where you obtained the lab.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Make sure you <strong>render a final copy with all your changes</strong> and work.</li>
<li>Look at your final html file to make sure it contains the work you expect and is formatted properly.</li>
</ul>
</div>
</div>
</section>
<section id="logging-out-of-the-server" class="level1">
<h1>Logging out of the Server</h1>
<p>There are many statistics classes and students using the Server. To keep the server running as fast as possible, it is best to sign out when you are done. To do so, follow all the same steps for closing Quarto document:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Save all your work.</li>
<li>Click on the orange button in the far right corner of the screen to quit <code>R</code></li>
<li>Choose <strong>don’t save</strong> for the <strong>Workspace image</strong></li>
<li>When the browser refreshes, you can click on the sign out next to your name in the top right.</li>
<li>You are signed out.</li>
</ul>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 9.2 (Plow)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scales_1.2.1    lubridate_1.9.2 forcats_1.0.0   stringr_1.5.0  
 [5] dplyr_1.1.2     purrr_1.0.2     readr_2.1.4     tidyr_1.3.0    
 [9] tibble_3.2.1    ggplot2_3.4.3   tidyverse_2.0.0 knitr_1.43     

loaded via a namespace (and not attached):
 [1] compiler_4.2.2    pillar_1.9.0      tools_4.2.2       digest_0.6.33    
 [5] timechange_0.2.0  jsonlite_1.8.7    evaluate_0.21     lifecycle_1.0.3  
 [9] gtable_0.3.4      pkgconfig_2.0.3   rlang_1.1.1       cli_3.6.1        
[13] rstudioapi_0.15.0 yaml_2.3.7        xfun_0.40         fastmap_1.1.1    
[17] withr_2.5.0       generics_0.1.3    vctrs_0.6.3       htmlwidgets_1.6.2
[21] hms_1.1.3         grid_4.2.2        tidyselect_1.2.0  glue_1.6.2       
[25] R6_2.5.1          fansi_1.0.4       rmarkdown_2.24    tzdb_0.4.0       
[29] magrittr_2.0.3    htmltools_0.5.6   colorspace_2.1-0  utf8_1.2.3       
[33] stringi_1.7.12    munsell_0.5.0    </code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>